services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/kleverson/src/app
    command: npm run start:dev
    ports:
      - "3000:3000"